version: "3.9"
services:
  db:
    image: iamtopcat/postgres:master-b71
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: beatmaps
      POSTGRES_USER: beatmaps
      POSTGRES_PASSWORD: "insecure-password"
    restart: always
  sessions:
    image: mongo:6-jammy
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./src/commonMain/resources/mongo:/docker-entrypoint-initdb.d:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: "root"
      MONGO_INITDB_ROOT_PASSWORD: "insecure-password"
      MONGO_INITDB_DATABASE: "beatmaps"
      MONGO_USER: "beatmaps"
      MONGO_PASSWORD: "insecure-password"
    restart: always
volumes:
  db_data:
  mongo_data:
